services:
  mariadb:
    build:
      context: requirements/mariadb
      args:
        - ROOTPASSWORD
        - DATABASENAME
        - DATABASEUSER
        - DATABASEPASSWORD
    image: mariadb
    container_name: mariadb
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: no-failure

  nginx:
    build: requirements/nginx
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - inception
    restart: no-failure

  wordpress:
    build: requirements/wordpress
    image: wordpress
    container_name: wordpress
    networks:
      - inception
    restart: no-failure

volumes:
  mariadb:
    driver: local
    name: mariadb
    driver_opts:
      o: bind
      type: none
      device: /home/naterrie/data/mariadb

  wordpress:
    driver: local
    name: wordpress
    driver_opts:
      o: bind
      type: none
      device: /home/naterrie/data/wordpress

networks:
  inception:
    driver: bridge
    name: inception
