services:

  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      args:
        - ROOTPASSWORD
        - DATABASENAME
        - DATABASEUSER
        - DATABASEPASSWORD
    image: mariadb
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    restart: on-failure

  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
    image: nginx
    env_file: .env
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    restart: on-failure

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
    image: wordpress
    env_file: .env
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    restart: on-failure

volumes:

  mariadb:
    driver: local
    name: mariadb
    driver_opts:
      o: bind
      type: none
      device: /home/naterrie/data/mariadb

  wordpress:
    driver: local
    name: wordpress
    driver_opts:
      o: bind
      type: none
      device: /home/naterrie/data/wordpress

networks:
  inception:
    driver: bridge
    name: inception
